name: Generate and Update RSS Feed

on:
  workflow_dispatch: # Pozwala na ręczne uruchomienie workflow z interfejsu GitHub
  schedule:
    # Uruchamia workflow codziennie o 03:00 UTC (czyli 05:00 w Polsce czasu letniego)
    # Możesz dostosować harmonogram, np. '0 */2 * * *' dla co 2 godziny
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest # Użyj najnowszej wersji Ubuntu

    steps:
    - name: Checkout repository # Klonuje Twoje repozytorium
      uses: actions/checkout@v4

    - name: Set up Python # Konfiguruje środowisko Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Użyj najnowszej wersji Pythona 3

    - name: Install dependencies # Instaluje biblioteki z requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to generate RSS
      run: python ALL_RADIO.py # Zmieniono nazwę pliku skryptu

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ALL_RADIO.xml # Zmieniono nazwę pliku XML
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
