name: Generate Radio Playlist RSS
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies # DODAJ TEN KROK
        run: pip install requests beautifulsoup4
      - name: Run Python script
        run: python radio_playlist.py
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add *.xml
          git diff --staged --quiet || git commit -m "Update radio playlist RSS"
          git push
